version : '3.5'
services:
 mysql:
  image: mysql
  restart: unless-stopped
  environment:
    MYSQL_ROOT_PASSWORD: developmentServerPassword
  ports:
  - "3306:3306"
  volumes:
    - "${PWD}/mysql:/var/lib/mysql"
